controller_list:
  - name: robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder1_joint
      - shoulder2_joint
      - shoulder3_joint
      - shoulder4_joint
      - shoulder5_joint
      - terminal_joint
  - name: test2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder1_joint
      - shoulder2_joint
      - shoulder3_joint
      - shoulder4_joint
      - shoulder5_joint
      - terminal_joint