# by bcc
controller_manager_ns: /
controller_list:
 - name: torso_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - shoulder_Joint
    - Arm_Joint
    - Forearm_Joint

# ends