# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: torso
  joint_model_group_pose: distancia
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_Joint
    - Arm_Joint
    - Forearm_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
torso_controller:
  type: position_controllers/JointPositionController
  joints:
    - shoulder_Joint
    - Arm_Joint
    - Forearm_Joint
  gains:
    shoulder_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Forearm_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1