robotcito_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder1_joint
    - shoulder2_joint
    - shoulder3_joint
    - shoulder4_joint
    - shoulder5_joint
    - terminal_joint
  gains:
    shoulder1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    terminal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1